[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"
noCache = true

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
